version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: flauc/firebase
    environment:
      NPM_VERSION: "6.9.0"
    steps:
      - checkout
      - run:
          name: Set Public Environment
          command: echo export const ENV_CONFIG=$PUBLIC_CONFIG > env-config.js
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
      - run:
          name: Install Shared dependencies
          command: yes | npm ci || true
      - run:
          name: Install Function dependencies
          command: yes | npm --prefix functions i || true
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
          paths:
            - node_modules
            - functions/node_modules
      - run:
          name: Set Firebase Environment
          command: npm run target-setup -- --token $FIREBASE_CI_TOKEN --project agrimatco-fb254
      - run:
          name: Building
          command: npm run build
      - save_cache:
          key: v1-dist-{{ .Branch }}-{{ .Revision }}
          paths:
            - package.json
            - package-lock.json
            - firebase.json
            - __sapper__
            - functions
            - static
            - .firebaserc
  deploy:
    docker:
      - image: flauc/firebase
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dist-{{ .Branch }}-{{ .Revision }}
            - v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "functions/package-lock.json" }}
      - run:
          name: Install dependencies if cache miss
          command: |
            if [ ! -d "node_modules" ]; then
              yes | npm ci || true
              yes | npm --prefix functions i || true
            fi
      - run:
          name: Set Firebase Environment
          command: npm run target-setup -- --token $FIREBASE_CI_TOKEN --project agrimatco-fb254
      - run:
          name: Deploy Master to Firebase
          command: firebase deploy --only hosting,functions:ssr --message "$CIRCLE_SHA1" --token $FIREBASE_CI_TOKEN --project agrimatco-fb254
workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
